#!/usr/bin/env bash
cat <<'EOF' > GEMINI.md
# Pawikan Sentinel – Unified Project File
> AI-powered sea-turtle detection on Raspberry Pi 4B with SMS alerts  
> Generated by merging `requirements.md`, `design.md`, and `tasks.md`

---

## 🔍 1. Requirements
EOF
cat requirements.md >> GEMINI.md

cat <<'EOF' >> GEMINI.md

---

## 🏗️ 2. Design & Architecture
EOF
cat design.md >> GEMINI.md

cat <<'EOF' >> GEMINI.md

---

## ✅ 3. Implementation Tasks & Progress
EOF
cat tasks.md >> GEMINI.md

echo "✅ GEMINI.md created!"
